// Code generated by protoc-gen-go. DO NOT EDIT.
// source: terra.proto

package chatpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TerraReq_ReqType int32

const (
	TerraReq_ENTER   TerraReq_ReqType = 0
	TerraReq_LEAVE   TerraReq_ReqType = 1
	TerraReq_MSGSEND TerraReq_ReqType = 2
)

var TerraReq_ReqType_name = map[int32]string{
	0: "ENTER",
	1: "LEAVE",
	2: "MSGSEND",
}

var TerraReq_ReqType_value = map[string]int32{
	"ENTER":   0,
	"LEAVE":   1,
	"MSGSEND": 2,
}

func (x TerraReq_ReqType) String() string {
	return proto.EnumName(TerraReq_ReqType_name, int32(x))
}

func (TerraReq_ReqType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b8db25aa1a93257c, []int{0, 0}
}

type TerraReq_Gender int32

const (
	TerraReq_UNKNOWN TerraReq_Gender = 0
	TerraReq_MALE    TerraReq_Gender = 1
	TerraReq_FEMALE  TerraReq_Gender = 2
)

var TerraReq_Gender_name = map[int32]string{
	0: "UNKNOWN",
	1: "MALE",
	2: "FEMALE",
}

var TerraReq_Gender_value = map[string]int32{
	"UNKNOWN": 0,
	"MALE":    1,
	"FEMALE":  2,
}

func (x TerraReq_Gender) String() string {
	return proto.EnumName(TerraReq_Gender_name, int32(x))
}

func (TerraReq_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b8db25aa1a93257c, []int{0, 1}
}

type TerraResp_RespStatus int32

const (
	TerraResp_STATUSOK     TerraResp_RespStatus = 0
	TerraResp_STATUSFAILED TerraResp_RespStatus = 1
)

var TerraResp_RespStatus_name = map[int32]string{
	0: "STATUSOK",
	1: "STATUSFAILED",
}

var TerraResp_RespStatus_value = map[string]int32{
	"STATUSOK":     0,
	"STATUSFAILED": 1,
}

func (x TerraResp_RespStatus) String() string {
	return proto.EnumName(TerraResp_RespStatus_name, int32(x))
}

func (TerraResp_RespStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b8db25aa1a93257c, []int{1, 0}
}

type TerraReq struct {
	Reqtype              TerraReq_ReqType `protobuf:"varint,1,opt,name=reqtype,proto3,enum=chatpb.TerraReq_ReqType" json:"reqtype,omitempty"`
	Id                   string           `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string           `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Message              string           `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Gender               TerraReq_Gender  `protobuf:"varint,5,opt,name=gender,proto3,enum=chatpb.TerraReq_Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TerraReq) Reset()         { *m = TerraReq{} }
func (m *TerraReq) String() string { return proto.CompactTextString(m) }
func (*TerraReq) ProtoMessage()    {}
func (*TerraReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8db25aa1a93257c, []int{0}
}

func (m *TerraReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerraReq.Unmarshal(m, b)
}
func (m *TerraReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerraReq.Marshal(b, m, deterministic)
}
func (m *TerraReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerraReq.Merge(m, src)
}
func (m *TerraReq) XXX_Size() int {
	return xxx_messageInfo_TerraReq.Size(m)
}
func (m *TerraReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TerraReq.DiscardUnknown(m)
}

var xxx_messageInfo_TerraReq proto.InternalMessageInfo

func (m *TerraReq) GetReqtype() TerraReq_ReqType {
	if m != nil {
		return m.Reqtype
	}
	return TerraReq_ENTER
}

func (m *TerraReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TerraReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *TerraReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TerraReq) GetGender() TerraReq_Gender {
	if m != nil {
		return m.Gender
	}
	return TerraReq_UNKNOWN
}

type TerraResp struct {
	Status               TerraResp_RespStatus `protobuf:"varint,1,opt,name=status,proto3,enum=chatpb.TerraResp_RespStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TerraResp) Reset()         { *m = TerraResp{} }
func (m *TerraResp) String() string { return proto.CompactTextString(m) }
func (*TerraResp) ProtoMessage()    {}
func (*TerraResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8db25aa1a93257c, []int{1}
}

func (m *TerraResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerraResp.Unmarshal(m, b)
}
func (m *TerraResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerraResp.Marshal(b, m, deterministic)
}
func (m *TerraResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerraResp.Merge(m, src)
}
func (m *TerraResp) XXX_Size() int {
	return xxx_messageInfo_TerraResp.Size(m)
}
func (m *TerraResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TerraResp.DiscardUnknown(m)
}

var xxx_messageInfo_TerraResp proto.InternalMessageInfo

func (m *TerraResp) GetStatus() TerraResp_RespStatus {
	if m != nil {
		return m.Status
	}
	return TerraResp_STATUSOK
}

func init() {
	proto.RegisterEnum("chatpb.TerraReq_ReqType", TerraReq_ReqType_name, TerraReq_ReqType_value)
	proto.RegisterEnum("chatpb.TerraReq_Gender", TerraReq_Gender_name, TerraReq_Gender_value)
	proto.RegisterEnum("chatpb.TerraResp_RespStatus", TerraResp_RespStatus_name, TerraResp_RespStatus_value)
	proto.RegisterType((*TerraReq)(nil), "chatpb.TerraReq")
	proto.RegisterType((*TerraResp)(nil), "chatpb.TerraResp")
}

func init() { proto.RegisterFile("terra.proto", fileDescriptor_b8db25aa1a93257c) }

var fileDescriptor_b8db25aa1a93257c = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x51, 0x6b, 0xc2, 0x30,
	0x14, 0x85, 0x6d, 0xa6, 0x69, 0xbd, 0x8a, 0x84, 0xfb, 0xb2, 0x30, 0xf6, 0x20, 0x7d, 0x12, 0x26,
	0x1d, 0xb8, 0xfd, 0x81, 0x82, 0x51, 0x86, 0x5a, 0x21, 0xad, 0xdb, 0x73, 0xd5, 0xe0, 0x64, 0xa8,
	0xb1, 0xc9, 0x1e, 0xfc, 0x17, 0xfb, 0xc9, 0xa3, 0xb1, 0xdd, 0x60, 0x7b, 0x09, 0xf7, 0x9c, 0xfb,
	0x85, 0x73, 0x48, 0xa0, 0x63, 0x55, 0x51, 0xe4, 0x91, 0x2e, 0x4e, 0xf6, 0x84, 0x74, 0xf3, 0x9e,
	0x5b, 0xbd, 0x0e, 0xbf, 0x08, 0x04, 0x59, 0xe9, 0x4b, 0x75, 0xc6, 0x11, 0xf8, 0x85, 0x3a, 0xdb,
	0x8b, 0x56, 0xdc, 0xeb, 0x7b, 0x83, 0xde, 0x88, 0x47, 0x57, 0x2c, 0xaa, 0x91, 0x48, 0xaa, 0x73,
	0x76, 0xd1, 0x4a, 0xd6, 0x20, 0xf6, 0x80, 0xec, 0xb7, 0x9c, 0xf4, 0xbd, 0x41, 0x5b, 0x92, 0xfd,
	0x16, 0xef, 0x20, 0x38, 0xee, 0x37, 0x1f, 0xc7, 0xfc, 0xa0, 0xf8, 0x8d, 0x73, 0x7f, 0x34, 0x72,
	0xf0, 0x0f, 0xca, 0x98, 0x7c, 0xa7, 0x78, 0xd3, 0xad, 0x6a, 0x89, 0x8f, 0x40, 0x77, 0xea, 0xb8,
	0x55, 0x05, 0x6f, 0xb9, 0xe0, 0xdb, 0x7f, 0xc1, 0x53, 0xb7, 0x96, 0x15, 0x16, 0x0e, 0xc1, 0xaf,
	0xaa, 0x60, 0x1b, 0x5a, 0x22, 0xc9, 0x84, 0x64, 0x8d, 0x72, 0x9c, 0x8b, 0xf8, 0x55, 0x30, 0x0f,
	0x3b, 0xe0, 0x2f, 0xd2, 0x69, 0x2a, 0x92, 0x31, 0x23, 0xe1, 0x03, 0xd0, 0xeb, 0xfd, 0xd2, 0x5e,
	0x25, 0xb3, 0x64, 0xf9, 0x96, 0xb0, 0x06, 0x06, 0xd0, 0x5c, 0xc4, 0xf3, 0x92, 0x06, 0xa0, 0x13,
	0xe1, 0x66, 0x12, 0x9e, 0xa0, 0x5d, 0xa5, 0x1a, 0x8d, 0xcf, 0x40, 0x8d, 0xcd, 0xed, 0xa7, 0xa9,
	0x5e, 0xe4, 0xfe, 0x4f, 0x31, 0xa3, 0xa3, 0xf2, 0x48, 0x1d, 0x23, 0x2b, 0x36, 0x1c, 0x02, 0xfc,
	0xba, 0xd8, 0x85, 0x20, 0xcd, 0xe2, 0x6c, 0x95, 0x2e, 0x67, 0xac, 0x81, 0x0c, 0xba, 0x57, 0x35,
	0x89, 0x5f, 0xe6, 0x62, 0xcc, 0xbc, 0x35, 0x75, 0x5f, 0xf2, 0xf4, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x58, 0x3f, 0x85, 0x95, 0xa1, 0x01, 0x00, 0x00,
}
